version: '2.1'

services:
  reactphp:
    build:
      context: .
    image: php_react:latest
    container_name: reactphp
    hostname: reactphp
    restart: unless-stopped
    ports:
      - '8881:80'

networks:
  default:
